{{- if and .Values.apiKey.value (not .Values.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hle-operator.fullname" . }}-api-key
  labels:
    {{- include "hle-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiKey.secretKey }}: {{ .Values.apiKey.value | quote }}
{{- end }}
